### PR TITLE
Close #95

### LINKED ISSUE #95: PMID:27254288
http://www.ncbi.nlm.nih.gov/pubmed/?term=The+Ankylosing+Spondylitis-associated+HLA-B*2705+presents+a+B*0702-restricted+EBV+epitope+and+sustains+the+clonal+amplification+of+cytotoxic+T+cells+in+patients

### PR DESCRIPTION
**Pull request by iziziz**
PMID_27254288

### CODE REVIEW

**Comment by iziziz** [comment]
there is no ANYmer-sort - so, there is no mhc.a
still there is donor mhc

**Comment by mikessh** [comment]
OK, maybe we can deduce B07 as the epitope is originally restricted to it.

**Comment by mikessh** [comment]
And note - there are some problems with header:
cdr3.alpha	v.alpha	j.alpha	cdr3.beta	v.beta	d.beta	j.beta	species	mhc.a	mhc.b	mhc.class	antigen.epitope	antigen.gene	antigen.species	reference.id	submitter	``optional columns that ensure correct confidence ranking of a given entry. Used to calculate a single confidence score, similar to transcript confidence level in ENSEMBL``	method.identification	method.frequency	method.singlecell	method.sequencing	method.verification	optional columns	meta.study.id	meta.cell.subset	meta.subset.frequency	meta.subject.cohort	meta.subject.id	meta.replica.id	meta.clone.id	meta.epitope.id	meta.tissue	meta.donor.MHC	meta.donor.MHC.method	meta.structure.id	comment

Please double-check the consistency

**Comment by iziziz** [comment]
guess we can't deduce B07-restriction:
there are TCRs from B*07 negative donors, but positive with B*2705
so, we can't distinguish between TCRs came from RPPIFIRRL-B*07 or RPPIFIRRL-B*2705

so, the chunk moved to "withheld" dir

**Pull request closed without merging**
