### PR TITLE
PMID_26800118

### LINKED ISSUE #125: PMID:26800118
http://www.ncbi.nlm.nih.gov/pubmed/26800118

there should be single--cell abTCR data

### PR DESCRIPTION
**Pull request by iziziz**
Close #125

### CODE REVIEW

**Comment by mikessh** [comment]
Looks like we have some problem with travis here. Will try to fix

**Comment by mikessh** [comment]
I've fixed the build system; now the fail is due to CDR3 sequence with ``X``

Some issues:

* Clones from different donors should be reported several times on different lines with different donor IDs
* The frequency should be appended with ``%`` symbol
* The fraction of CD8 -- never use ``,`` as digit separator
* There are fewer entries in the submission than in the table 4 of the paper -- why is that? (note that there are several tables with sequences in the paper so I expect even more entries)

**Comment by iziziz** [comment]
Started another branch... Sorry. Have no idea what to do with this, just close this branch?

**Comment by mikessh** [comment]
Yes, just closing it is OK

**Pull request closed without merging**
